### ISSUE TITLE
add version support for all platforms

### ISSUE THREAD

**Issue by kernelsam** [senzing-factory/github-action-install-senzing-api#52]
# Objective

We need to be able to concurrently test release and development versions of senzing. 

# 2/27 Updates

- rename latest to production
- require major version specification 
```
- production-v3
- production-v4
- staging-v3
- staging-v4
- 3.8.0
- 3.8.0-12345
- 3.8.1
- 3.8.1-12345
- 3.8.2
- 3.9.0
- 4.0.0 - A future tag
- 4.1.0 - A future tag
- etc.
```

# Initial request from @docktermj 

## Windows

- latest - currently 3.8.x, represents what is "latest" to customer
- staging - currently 3.8.x, represents the "next release" for customer
- staging-v4 - Work being done on V4 which is not a publicly supported Senzing release, yet.  Goes away after V4 is public.
- latest-v3 - a future label that is created when V4 is the latest, i.e. not used yet

## Darwin

- latest
- staging
- staging-v4
- latest-v3

## Linux

- latest
- staging
- staging-v4
- latest-v3
- 3.8.0
- 3.8.1
- 3.8.2
- 3.9.0
- 4.0.0 - A future tag
- 4.1.0 - A future tag
- etc.

**Comment by docktermj** [comment]
@kernelsam Here's a list of failing pull requests that can be used for testing:

- https://github.com/pulls/assigned?page=1&q=is%3Aopen+is%3Apr+archived%3Afalse+assignee%3Adocktermj

**Comment by kernelsam** [comment]
Closing as completed.
